version: 2

jobs:
  macos:
    macos:
      xcode: "9.0"
    steps:
      - run: brew install vapor/tap/vapor vapor/tap/cmysql
      - run: brew services start mysql
      - run: sleep 3 && mysqladmin -uroot create test
      - checkout
      - run: swift build
      - run: swift test

  linux:
    docker:
      - image: swift:4.0.3
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
    steps:
      - run: apt-get update
      - run: apt-get install -y libmysqlclient-dev libssl-dev
      - checkout
      - run: swift build
      - run: swift test

  # 3.1 backward compat checks

  linux-3:
    docker:
      - image: swift:3.1.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: test
    steps:
      - run: apt-get update
      - run: apt-get install -y libmysqlclient-dev libssl-dev
      - checkout
      - run: swift build
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-3
      - macos
